### ISSUE TITLE
Use a defined environment variable in place of `apikey` if it exists

### ISSUE THREAD

**Issue by kaihoffman** [civo/cli-go#232]
Instead of requiring `civo apikey save` for every environment, have it so that the system will use the API key defined in an environment variable if it exists. This means you would be able to configure the env var for a CI/CD system once, download Civo CLI and have it automatically look at the defined variable for the appropriate key to use.

Suggested names for the variable:

- CIVO_APIKEY
- CIVO_TOKEN

(proposed by @rawkode)

**Comment by alejandrojnm** [comment]
This is done

**Comment by kaihoffman** [comment]
Which of the variable names does it look for @alejandrojnm ? Just so we can update the README

**Comment by alejandrojnm** [comment]
So sorry @kaihoffman I forget to mention we go with CIVO_TOKEN

**Comment by kaihoffman** [comment]
Has this been built into a release @alejandrojnm @satakshigarg ? I don't see the documentation on the README and the latest release seems to have been made 23 days ago.

**Comment by alejandrojnm** [comment]
I think this is will be in the next release. We need update the doc.

**Comment by kaihoffman** [comment]
I could update the docs but with the merge having happened it'd be weird being in the readme if that's not how the app works.

**Comment by alejandrojnm** [comment]
You can add and create a PR and add to master, and when the release come out it will be there

**Comment by kaihoffman** [comment]
That's what i mean though, will it be merged at the same time as you cut the release? Because if it's before, I might as well push it now?
